apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.container.envs }}
  {{ $key | upper }}: {{ $value | quote}}
{{- end }}
