{{- if .Values.rbac.create -}}
apiVersion: {{ include "app.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "app.serviceAccountName" . }}
  namespace: {{ template "app.namespace" . }}
{{- end }}
