{{- if .Values.rbac.create -}}
apiVersion: {{ include "app.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.rbac.rules }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
{{- else }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
{{- end }}
{{- end }}
