apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hardened-node-application
  namespace: hardened-node-application
spec:
  values:
    container:
      envs:
        NODE_ENV: "non-production"
        STATD_HOST: "graphite.graphite.svc.cluster.local"
