apiVersion: v2
name: app
description: App chart
type: application
version: 1.0.0
kubeVersion: ^1.21.0-0
maintainers:
- email: patcharapon.boo@gmail.com
  name: Patcharapon Booonsiri
dependencies:
  - name: common
    version: 1.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
