replicas: 2

nameOverride: "app"
fullnameOverride: "app"
namespaceOverride: "tmp"

image:
  repository: dummy/dummy
  tag: "dummy"
  imagePullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789000:role/iam-role-name-here
  autoMount: true

## See `kubectl explain deployment.spec.strategy` for more
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
deploymentStrategy:
  type: RollingUpdate

container:
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /api/health/
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /api/health/
      port: http

  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false

  envs:
    FOO: "bar"

  envFromConfigMap: tmp

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  ## Container Lifecycle Hooks. Execute a specific bash command or make an HTTP request
  lifecycleHooks: {}
    # postStart:
    #   exec:
    #     command: []

## Expose the service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  type: ClusterIP
  annotations: {}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

ingresses:
  enabled: true
  ingress:
    - annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: default-allow-vpn-and-office-ips@kubernetescrd
      hosts:
        - host: "dummy.atato.com"
          paths:
            - path: "/"
              pathType: "Prefix"
            - path: "/test"
              pathType: "Prefix"
              backendService: tmp
              backendPort: 3000
      tls:
        - secretName: dummy-tls-cert
          hosts:
            - dummy.atato.com

securityContext: {}

rbac:
  create: true
  rules: []

# Apply extra labels to common labels.
extraLabels: {}

## Pod Annotations
podAnnotations: {}

## Pod Labels
podLabels: {}

## Deployment annotations
annotations: {}

## See `kubectl explain poddisruptionbudget.spec` for more
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: 1

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector:
  dummy: "dummy"

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"

## @param podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAffinityPreset: ""

## @param podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft

## Node affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  ## @param nodeAffinityPreset.type Node affinity preset type. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ##
  type: ""
  ## @param nodeAffinityPreset.key Node label key to match. Ignored if `affinity` is set.
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## @param nodeAffinityPreset.values Node label values to match. Ignored if `affinity` is set.
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

## @param affinity Affinity for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## Note: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
##
affinity: {}

## Topology Spread Constraints
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
##
topologySpreadConstraints: []

terminationGracePeriodSeconds: 60

volumes:
  - name: dummy
    secret:
      secretName: dummy

volumeMounts:
  - name: dummy
    mountPath: /home/dummy
    readOnly: true

extraReadOnlyFiles:
  - volumeName: "tmp"
    mountPath: "tmp"
    files:
      foo.txt: |
        bla
      bar.txt: |
        bla

## Number of old ReplicaSets to retain
##
revisionHistoryLimit: 10

vpa:
  enabled: false

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceMonitor:
  enabled: true
  path: "/health"
  port: 8080
  interval: 5s
  timeout: 3s
  labels:
    FOO: bar
  annotations:
    FOO: bar
