apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      version: "1.15.x"
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 60m
  install:
    crds: CreateReplace
    disableWait: true
  upgrade:
    crds: CreateReplace
    disableWait: true
