apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    routingMode: native
    ipam:
      mode: eni
    eni:
      enabled: true
    egressMasqueradeInterfaces: eth0
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
